"""show migration

Revision ID: 0710ac9a1092
Revises: 08a695fc64ec
Create Date: 2023-07-29 13:18:26.092931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0710ac9a1092'
down_revision = '08a695fc64ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
