"""New Migration

Revision ID: 1369876c1c6f
Revises: 99eeadf04ab6
Create Date: 2023-07-29 12:55:20.466729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1369876c1c6f'
down_revision = '99eeadf04ab6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
