"""show migration

Revision ID: 43a3855ad08d
Revises: bd91dd8dc1f6
Create Date: 2023-07-29 13:15:36.208620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43a3855ad08d'
down_revision = 'bd91dd8dc1f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
