"""show migration

Revision ID: 6ba4d87086c7
Revises: ff52253e4332
Create Date: 2023-07-29 23:51:44.578668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ba4d87086c7'
down_revision = 'ff52253e4332'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('passwordHash', sa.String(), nullable=True))
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user', 'passwordHash')
    # ### end Alembic commands ###
