"""New Migration

Revision ID: 99eeadf04ab6
Revises: 115088add971
Create Date: 2023-07-29 00:08:51.736894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99eeadf04ab6'
down_revision = '115088add971'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
